<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $categories = array(
            array('id' => '1','user_id' => '1','category_name' => 'Development','slug' => 'development','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '2','user_id' => '1','category_name' => 'Mobile App','slug' => 'mobile-app','category_id' => '1','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '3','user_id' => '1','category_name' => 'Android','slug' => 'android','category_id' => '2','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '4','user_id' => '1','category_name' => 'Data Science','slug' => 'data-science','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '5','user_id' => '1','category_name' => 'Deep Learning','slug' => 'deep-learning','category_id' => '4','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '6','user_id' => '1','category_name' => 'Machine Learning','slug' => 'machine-learning','category_id' => '5','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '7','user_id' => '1','category_name' => 'Amazon Web Services','slug' => 'amazon-web-services','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '8','user_id' => '1','category_name' => 'AWS Cloud Architecture','slug' => 'aws-cloud-architecture','category_id' => '7','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '9','user_id' => '1','category_name' => 'AWS-Cloud Platform','slug' => 'aws-cloud-platform','category_id' => '8','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '11','user_id' => '1','category_name' => 'Other IT & Software','slug' => 'other-it-software','category_id' => '10','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '12','user_id' => '1','category_name' => 'Programming Fundamentals','slug' => 'programming-fundamentals','category_id' => '11','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '13','user_id' => '1','category_name' => 'Business','slug' => 'business','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '14','user_id' => '1','category_name' => 'Entrepreneurship','slug' => 'entrepreneurship','category_id' => '13','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '15','user_id' => '1','category_name' => 'Online Business','slug' => 'online-business','category_id' => '14','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '16','user_id' => '1','category_name' => 'Personal Development','slug' => 'personal-development','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '17','user_id' => '1','category_name' => 'Personal Productivity','slug' => 'personal-productivity','category_id' => '16','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '18','user_id' => '1','category_name' => 'Time Management','slug' => 'time-management','category_id' => '17','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '19','user_id' => '1','category_name' => 'Database Management','slug' => 'database-management','category_id' => '11','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '21','user_id' => '1','category_name' => 'Programming Languages','slug' => 'programming-languages','category_id' => '1','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '22','user_id' => '1','category_name' => 'Java','slug' => 'java','category_id' => '21','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '23','user_id' => '1','category_name' => 'Network & Security','slug' => 'network-security','category_id' => '11','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '24','user_id' => '1','category_name' => 'IT & Software','slug' => 'it-software','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '25','user_id' => '1','category_name' => 'Network & Security','slug' => 'network-security-1','category_id' => '24','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '26','user_id' => '1','category_name' => 'Ethical Hacking','slug' => 'ethical-hacking','category_id' => '25','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '27','user_id' => '1','category_name' => 'Data Science','slug' => 'data-science-1','category_id' => '1','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '28','user_id' => '1','category_name' => 'Deep Learning','slug' => 'deep-learning-1','category_id' => '27','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '29','user_id' => '1','category_name' => 'Communication','slug' => 'communication','category_id' => '13','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '30','user_id' => '1','category_name' => 'Writing','slug' => 'writing','category_id' => '29','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '31','user_id' => '1','category_name' => 'Frontend','slug' => 'frontend','category_id' => '1','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '32','user_id' => '1','category_name' => 'Html &CSS','slug' => 'html-css','category_id' => '31','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '33','user_id' => '1','category_name' => 'WebDevelopment','slug' => 'webdevelopment','category_id' => '1','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '34','user_id' => '1','category_name' => 'JavaScript','slug' => 'javascript','category_id' => '33','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '35','user_id' => '1','category_name' => 'Front End Web Development','slug' => 'front-end-web-development','category_id' => '33','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '36','user_id' => '1','category_name' => 'IT Networking Fundamentals','slug' => 'it-networking-fundamentals','category_id' => '25','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '37','user_id' => '1','category_name' => 'Health & Fitness','slug' => 'health-fitness','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '38','user_id' => '1','category_name' => 'General Health','slug' => 'general-health','category_id' => '37','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '39','user_id' => '1','category_name' => 'Breathing Techniques','slug' => 'breathing-techniques','category_id' => '38','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '40','user_id' => '1','category_name' => 'Others','slug' => 'others','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '41','user_id' => '1','category_name' => 'Visual','slug' => 'visual','category_id' => '40','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '42','user_id' => '1','category_name' => 'Photography','slug' => 'photography','category_id' => '41','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '43','user_id' => '1','category_name' => 'Finance & Accounting','slug' => 'finance-accounting','category_id' => '0','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '0','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '44','user_id' => '1','category_name' => 'Investing & Trading','slug' => 'investing-trading','category_id' => '43','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '45','user_id' => '1','category_name' => 'Technical Analysis','slug' => 'technical-analysis','category_id' => '44','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '46','user_id' => '1','category_name' => 'Career Development','slug' => 'career-development','category_id' => '40','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '47','user_id' => '1','category_name' => 'Interviewing Skills','slug' => 'interviewing-skills','category_id' => '46','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '48','user_id' => '1','category_name' => 'Cryptocurrency & Blockchain','slug' => 'cryptocurrency-blockchain','category_id' => '43','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '49','user_id' => '1','category_name' => 'Cryptocurrency','slug' => 'cryptocurrency','category_id' => '48','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '50','user_id' => '1','category_name' => 'Programming 101','slug' => 'programming-101','category_id' => '21','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '51','user_id' => '1','category_name' => 'iOS','slug' => 'ios','category_id' => '2','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '53','user_id' => '1','category_name' => 'Database','slug' => 'database','category_id' => '1','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '1','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43'),
            array('id' => '54','user_id' => '1','category_name' => 'SQL','slug' => 'sql','category_id' => '53','thumbnail_id' => NULL, 'category_image' => NULL, 'title' => '', 'description' => '', 'is_top' => 0, 'icon_class' => '0','step' => '2','status' => '1', 'created_at' => '2021-12-23 02:20:36','updated_at' => '2021-12-29 01:45:43')
        );

        \Illuminate\Support\Facades\DB::table('categories')->insert(
            $categories
        );
        
    }
}
